### ISSUE TITLE
Hard to maintain ! Like how to upgrade or maintain from old version ?

### ISSUE THREAD

**Issue by LTFENG** [aissat/easy_localization#151]
I personal don't like this plugin even though this plugin is good and easy to use.
but the author changes or updates the plugin without considering the upgrading part ?

I follow from Localizations.of(context).tr('KEY', args[]) to 'KEY'.tr(), and now what ?

OMG, nightmare for me if upgrading.

**Comment by aissat** [comment]
@LTFENG  u can use `Localization.of(context).tr('KEY', args[])`

**Comment by HugoHeneault** [comment]
We're also sometimes encountering issues upgrading this plugin. I know it is still in development since you published 1.x it should not change its APIs without a major version update. 
 
@aissat I think you should enforce [semantic versioning](https://semver.org/spec/v2.0.0-rc.1.html), as advised on [Dart Pub doc](https://dart.dev/tools/pub/versioning#semantic-versions)

Migrating from 2.1.x to 2.2.x broke our app, with the `I/flutter (19483): NoSuchMethodError: The getter 'languageCode' was called on null.` as said on #152. It's easy to fix but still, it's not always comfortable. 

You're doing a great job here (thanks again!), more and more people are going to use it and if you wanna avoid them talking about "nightmare" it might be the way :)

**Comment by Overman775** [comment]
@LTFENG #152 fixed
