### ISSUE TITLE
No MaterialLocalizations found

### ISSUE THREAD

**Issue by CyberGhost007** [aissat/easy_localization#249]
```
No MaterialLocalizations found.
DropdownButton<LanguageModel> widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
```

My Code: 
`
class LanguageChanger extends StatefulWidget {
  final EdgeInsets margin;
  final BuildContext ctx;
  LanguageChanger({Key key, this.margin, this.ctx}) : super(key: key);

  @override
  _LanguageChangerState createState() => _LanguageChangerState();
}

class _LanguageChangerState extends State<LanguageChanger> {
  List<LanguageModel> languages = [
    LanguageModel(name: 'English', code: 'us'),
    LanguageModel(name: 'Hindi', code: 'in'),
    LanguageModel(name: 'Chinese', code: 'cn'),
    LanguageModel(name: 'French', code: 'fr'),
    LanguageModel(name: 'Spanish', code: 'es'),
    LanguageModel(name: 'German', code: 'de'),
    LanguageModel(name: 'Japanese', code: 'jp'),
    LanguageModel(name: 'Turkish', code: 'tr'),
    LanguageModel(name: 'Russian', code: 'ru'),
    LanguageModel(name: 'Vietnamese', code: 'vn'),
  ];

  LanguageModel _selectedLang;

  @override
  Widget build(BuildContext context) {
    MaterialLocalizations.of(context);

    return Material(
      child: Container(
        margin: widget.margin ?? EdgeInsets.all(0),
        padding: EdgeInsets.all(8),
        decoration: BoxDecoration(
          border: Border.all(
            width: 0.5,
            color: Colors.grey[300],
          ),
          borderRadius: BorderRadius.circular(8),
        ),
        child: DropdownButton<LanguageModel>(
          value: _selectedLang ?? languages[0],
          isDense: true,
          underline: Center(),
          onChanged: (LanguageModel newValue) {
            switch (newValue.code) {
              case 'us':
                context.locale = Locale('en', 'EN');
                break;
              case 'in':
                context.locale = Locale('hi', 'IN');
                break;
              case 'cn':
                context.locale = Locale('zh');
                break;
              case 'fr':
                context.locale = Locale('fr');
                break;
              case 'es':
                context.locale = Locale('es');
                break;
              case 'de':
                context.locale = Locale('de');
                break;
              case 'jp':
                context.locale = Locale('ja');
                break;
              case 'tr':
                context.locale = Locale('tr', 'TR');
                break;
              case 'ru':
                context.locale = Locale('ru');
                break;
              case 'vn':
                context.locale = Locale('vn', 'VN');
                break;
              default:
                context.locale = Locale('en', 'EN');
            }
            setState(() {
              _selectedLang = newValue;
            });
          },
          items: languages.map((LanguageModel value) {
            return DropdownMenuItem<LanguageModel>(
              value: value,
              child: Row(
                children: [
                  Flag(
                    value.code,
                    height: 24,
                    width: 24,
                  ),
                  SizedBox(width: 8),
                  DynamicText(
                    text: value.name,
                    fontSize: 14,
                  ),
                ],
              ),
            );
          }).toList(),
        ),
      ),
    );
  }
}
`

**Comment by Overman775** [comment]
@CyberGhost007 you forgeret add delegates 

```
MaterialApp(
      localizationsDelegates: context.localizationDelegates,
```

**Comment by cchamnab** [comment]
I've added delegate but still got "No MaterialLocalizations found"

**Comment by TypingMonkey** [comment]
Hey @Kendokai ,

I have experienced the same issue as you and found out that it was because I used a language code that is not supported by the flutter_localization-library. You can find the list of supported languages and the language code that is used to get the specific locale here: https://api.flutter.dev/flutter/flutter_localizations/flutter_localizations-library.html
Looking at your code, it looks like your code will break if the user selects Vietnamese, because you use a different code for your vietnamese than as how it is supported by the  flutter_localization-library. 

If you change 
`context.locale = Locale('vn', 'VN');`
to: 
` context.locale = Locale('vi', 'VN');`
your code should work.

I have written an answer on a related ticket here that gives more information: https://github.com/aissat/easy_localization/issues/220#issuecomment-846035493

@aissat perhaps the easy localization library can give the developer a warning in case he wants to add a Locale('xyz') that  'xyz' is not supported by the  flutter_localization-library? Currently setting the locale to Locale('xyz') throws the error "No MaterialLocalizations found", that does not help to find this issue.

**Comment by sgruhier** [comment]
Thanks! I had same issue with Korean. I used `kr` instead of `ko`
