### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by 3rsin3rgul** [aissat/easy_localization#305]
Hello, 
I cannot update the pub because of the version solving error.
This is yaml file:
` firebase: ^7.3.0
  firebase_core: 0.5.0
  firebase_auth: 0.18.0
  cloud_firestore: 0.14.0
  firebase_storage: "^4.0.0"
  easy_localization: ^2.3.3+1
  easy_localization_loader: ^0.0.2`

This is error:
`Because firebase_auth 0.18.0 depends on firebase_auth_web ^0.3.0 which depends on intl ^0.16.1, firebase_auth 0.18.0 requires intl ^0.16.1.

And because easy_localization >=2.1.0+1 depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, firebase_auth 0.18.0 is incompatible with easy_localization >=2.1.0+1.

So, because student depends on both firebase_auth 0.18.0 and easy_localization ^2.3.3+1, version solving failed.
pub get failed (1; So, because student depends on both firebase_auth 0.18.0 and easy_localization ^2.3.3+1, version solving failed.)`

**Comment by aissat** [comment]
@3rsin3rgul  try overrides `intl` version in ur `pubspec.yaml`

```
dependency_overrides:
  intl: 0.16.0
```

**Comment by kyounglee** [comment]
If the above solution ( dependency_overrides ) applied, another problem occurs (build FAILURE).

This is the output of build
----------
Running Gradle task 'assembleDebug'...
/~~/flutter/packages/flutter_localizations/lib/src/material_localizations.dart:413:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$selectedRowCount', formatDecimal(selectedRowCount));
      ^^^^^^^^^^^^
/~~/flutter/packages/flutter_localizations/lib/src/material_localizations.dart:550:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$licenseCount', formatDecimal(licenseCount));
      ^^^^^^^^^^^^
/~~/flutter/packages/flutter_localizations/lib/src/material_localizations.dart:659:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$remainingCount', formatDecimal(remainingCount));
      ^^^^^^^^^^^^

FAILURE: Build failed with an exception.

----------
about my .yaml
<pre>
   ::::: ( some omitted )

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^2.3.3+1
  intl : ^0.17.0-nullsafety.2
  ::::: ( some omitted )
dependency_overrides:
  intl: 0.16.0
</pre>
