### ISSUE TITLE
Can't localize constant widgets

### ISSUE THREAD

**Issue by fernando-s97** [aissat/easy_localization#433]
This **example** code would never rebuild:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: const MyWidget(), // If I remove the "const" here, it'll work
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget();
  
  @override
  Widget build(BuildContext context) {
    return Text(
      'Hello, World!'.tr(),
      style: Theme.of(context).textTheme.headline4,
    );
  }
}
```

Any way to avoid that?

My main problem with that is that I can only detect this during in runtime. There is any way to make it a compile time error or something like that? I want flutter to know that this widget can't be a constant one, or else the localization will fail.

**Comment by jonafeucht** [comment]
I'm really confused as to what you want fixed?
A const is by default immutable and since localization is obviously mutable, it will of course never rebuild.

**Comment by na-si** [comment]
[fernando-s97](https://github.com/fernando-s97), I've met the same problem.  

I don't like removing const words, because It's hard to control every const word in our code.
Widgets could be nested and some text views could be inside a few widgets -for example,  `(widget(...(widget (text...)`(it's pseudo-code). What should we have to do in this case? Should we remove the const word in every parent widget above the text widget inside this tree? 

Unfortunately, I don't find any good solution for now. But if you add a key to the text widget
`Text(key: ValueKey(key: ValueKey(context.locale.languageCode,....)`, it will be rebuilt. I don't like this solution, but in my opinion, it is better to control, than the const word.

I'm still looking for a better solution.

**Comment by fernando-s97** [comment]
Nice workaround @na-si. For now I think this is the best solution to this problem

**Comment by DartAndrik** [comment]
> I'm really confused as to what you want fixed? A const is by default immutable and since localization is obviously mutable, it will of course never rebuild.

Yes you are right but the localization changes really rarely and it should works correct. So why i should ignore provided by `const` rebuild optimization to get the correct worked localization. We can change for example Theme even in `const` widgets with  `Theme.of(context)`. And self-made solution with Inherited widget works fine. But why i can't use it just "out of the box"?
And of course :
```dart
const Text(
  LocaleKeys.language,
).tr()
```
this solution also will not work. And my project lint rules are requiring to use 'const' wherever it possible and i agree with this. 
So it would be nice to have something like 
```dart
Text(Easylocalization.of(context).translate('some_unique_translation_key'))
```
(and then, maybe, even shorter 
```dart
Text(context.translate('some_unique_translation_key'))
```
)
as a package feature :)
