### ISSUE TITLE
Add comments lines to the translation json file

### ISSUE THREAD

**Issue by giogithub89** [aissat/easy_localization#543]
Hey, I know that json file does not allows to add comments, but is there a way to do it for Easy localization? Most of the time the translation files are too big and difficult to read. I would like to add comments lines in order to separate the translation file based on my flutter screens. Thanks

Example:
`//screen 1
{"settings": "Settings"}
//screen 2
{"welcome": "Benvenuto"}`

**Comment by dJani97** [comment]
JSON as a standard does not support comments, so supporting this would:
- require them to come up with a whole new parser instead of using a built-in one
- make the json files unreadable by external services, libraries, IDEs, etc.

But `easy_localization` can read multiple formats, including `.xml` or `.yaml`, all of which support comments.

Alternatively, this library supports nesting, so you could refactor your code this way:

```json
{
  "screen1":{
    "settings":"Settings"
  },
  "screen2":{
    "welcome":"Benvenuto"
  }
}
```

And then access these keys in your code like so: `"screen2.welcome".tr()`
