### ISSUE TITLE
PLease update dependencies

### ISSUE THREAD

**Issue by urmamb** [aissat/easy_localization#549]
depends on easy_localization 3.0.1 which depends on intl >=0.17.0-nullsafety <=0.17.0, intl >=0.17.0-nullsafety <=0.17.0 is required.
So, because ***** depends on intl 0.18.0, version solving failed.

**Comment by aissat** [comment]
@urmamb  is done check this [3.0.2-dev.1](https://pub.dev/packages/easy_localization/versions/3.0.2-dev.1)

**Comment by MichalNemec** [comment]
3.0.2-dev.1 still has issues.
```
Because reactive_date_time_picker >=0.6.0 depends on intl ^0.18.0 and easy_localization >=3.0.2-dev.1 depends on intl ^0.17.0, reactive_date_time_picker >=0.6.0 is incompatible with easy_localization >=3.0.2-dev.1.
So, because ... depends on both easy_localization 3.0.2-dev.1 and reactive_date_time_picker ^0.6.1, version solving failed.
```

**Comment by aissat** [comment]
@urmamb  is done check this [3.0.2-dev.1](https://pub.dev/packages/easy_localization/versions/3.0.2-dev.1)

> 3.0.2-dev.1 still has issues.
> 
> ```
> Because reactive_date_time_picker >=0.6.0 depends on intl ^0.18.0 and easy_localization >=3.0.2-dev.1 depends on intl ^0.17.0, reactive_date_time_picker >=0.6.0 is incompatible with easy_localization >=3.0.2-dev.1.
> So, because ... depends on both easy_localization 3.0.2-dev.1 and reactive_date_time_picker ^0.6.1, version solving failed.
> ```

Unfortunately, we cannot use intl version 0.18.0 as the `flutter_localizations` package in the Flutter SDK depends on intl version 0.17.0. The `flutter_localizations` package requires `intl` version 0.17.0 for proper functioning and cannot work with any other version of `intl` check this https://github.com/flutter/flutter/issues/117163

I try to change the dependency to allow both `intl` versions 0.17.0 and 0.18.0, you should be able to use the latest version of intl while still maintaining compatibility with the `flutter_localizations` package. Since 0.18.0 doesn't have any breaking changes, this [3.0.2-dev.2](https://pub.dev/packages/easy_localization/versions/3.0.2-dev.2) should work without any issues.
this solution from https://github.com/rwbr/flutter_neat_and_clean_calendar/pull/50
