### ISSUE TITLE
Minimize the use of external libraries 

### ISSUE THREAD

**Issue by aissat** [aissat/easy_localization#62]
@spiritinlife @danilofuchs 
My suggestions
 - remove `SharedPreferences` it is better to use it  from out PKG

**Comment by spiritinlife** [comment]
Hmm am not sure about this one @aissat .
Is there any other alternative to SharedPreferences? 
Also imho this is something that should be handled and properly maintained by easy_localization. It is easy_localization's responsibility to save the last locale used and how this is done is not something that the developer should care about.

**Comment by danilofuchs** [comment]
Agreed with @spiritinlife. `SharedPreferences` is used to save the last locale, and that's a desired behaviour.

**Comment by danilofuchs** [comment]
Closing this as currently, we only depend on `intl` and `shared_preferences`. We can safely assume any lib customer would depend on these libraries anyway, and we use them in justifiable ways.

**Comment by ibrahimdevs** [comment]
Hey @aissat @spiritinlife @danilofuchs ,
It is a closed issue but I want to propose rethink about it again. People (including me) may think about to provide this functionality with another method. For example, I'm using hive db, and want to persist locale with hive. I have to load shared_preferences because of only this package.

Maybe you can define an interface as;

```
abstract class EasyLocalePersistanceManager {
  Future<void> saveLocale(Locale? locale);
  Future<void> initEasyLocation();
  Future<void> deleteSaveLocale();
}
```

And then call this class methods in easy_localization_controller
then can provide an example implementation of EasyLocalePersistanceManager with SharedPreferences.

What do you think about it?


Thanks,

**Comment by spiritinlife** [comment]
Hey all, haven't contributed for a while in this project but I have to say that what you propose makes sense. Easy localization could easily just expose an interface with a memory based storage implementation and let the developer provide their own. I believe fresh does something similar for authentication tokens.

It's nice to see how flutter storage solutions have evolved in those 3 years.

**Comment by aissat** [comment]
I totally agree, It is actually in our plans, will implement it soon.
Thanks
